config {  
  type: "table",
  schema: "Demo_STR_MP",
  dependencies: ["MP_GETVIEW_Projects_001"],
  tags: ["t_snapshot_daily"]}

SELECT
 * EXCEPT(ROW,record_deleted,bg,cyber_security_level),
 CASE 
 WHEN bg_code='10B' THEN 'CDA'
 WHEN bg_code='20B' THEN 'PTS'
 WHEN bg_code='30B' THEN 'THS'
 WHEN bg_code='40B' THEN 'VIS'
 ELSE bg
 END AS bg
FROM 
 (
   SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY id ORDER BY sync_time DESC) AS ROW,
   FROM `bq_integration_eu.BQ_Projects_Sync` --${ref("MP_GETVIEW_Projects_001")} 
 )
WHERE ROW=1 AND record_deleted =FALSE